
FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app/package*.json ./
RUN npm install --only=production

# Copy compiled JS files
COPY --from=builder /app/dist ./dist

# Copy connection profile & wallet if needed
COPY fabric-samples/test-network/organizations ./organizations
COPY wallet ./wallet

EXPOSE 3000
CMD ["node", "dist/app.js"]
